apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-server
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    run: hello-server
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: hello-server